/**
 * Wake scheduler — listens to CH_MESSAGE_NEW (Redis pubsub) and
 * routes wake events to the right agent's BYOA daemon.
 *
 * Model (BYOA-only, ADR 0003):
 *   1. Try deliverWake() — push the SSE event to the agent's
 *      connected daemon over its wake-stream.
 *   2. If 0 subscribers, the daemon host is offline/asleep. There is
 *      nothing to spin up — the wake is durable via the inbox, so the
 *      daemon catches up on its next reconnect drain.
 *
 * Per-agent serialization is intrinsic — each agent has exactly one
 * daemon, which runs one turn at a time (see computer/daemon.ts).
 */
import { pool } from '../db/pool.js'
import { env } from '../env.js'
import { CH_MESSAGE_NEW, CH_POLLS, CH_TYPING, publish, redis, sub, type MessageNewEvent, type PollUpdatedEvent } from '../redis.js'
import { isAgent } from './personas.js'
import { deliver as deliverWake, deliverSteer, type PollWakeBrief } from './runtime/wake-bus.js'
import { isAgentBusy } from './runtime/inproc-client.js'
import { Semaphore } from '../concurrency.js'

/** Bounds how many recipients the wake fan-out triages + wakes at once
 *  (per replica). See env.WAKE_FANOUT_CONCURRENCY — this is the
 *  backpressure that stops a swarm reply-storm from oversubscribing the
 *  pg pool and tripping the triage fail-open amplification loop. */
const wakeFanoutSem = new Semaphore(env.WAKE_FANOUT_CONCURRENCY)

/** Optional payload attached to a wake that the busy-agent path should
 *  also publish as a `steer` event so the running turn can react
 *  mid-flight (instead of waiting until the next wake). Built by the
 *  message-new handler from MessageNewEvent. */
export interface SteerWakePayload {
  messageId: string
  conversationId: string
  authorName: string
  body: string
  /** Tenant tag so the steer-ack typing broadcast routes to clients instead of
   *  being dropped as "untagged". Sourced from the message-new event. Optional
   *  only so test fixtures can omit it; the production wake() path always sets it. */
  companyId?: string
}

type WakeReason = 'message.new' | 'idle' | 'manual' | 'background_scan' | 'poll.updated'

/** Options attached to a wake. Carried on the wake payload; the daemon's
 *  turn consumes them (it re-triages locally, so there is no server-side
 *  triage note anymore). */
export interface WakeOptions {
  /** Short scheduler note rendered only for idle synthetic wakes. */
  idleReason?: string
  /** Internal background brief rendered as a normal model input. */
  backgroundBrief?: {
    title: string
    body: string
    source?: string
  }
  /** Snapshot of a poll the author should look at right now — set when
   *  trigger === 'poll.updated'. Same shape as the wake-bus brief. */
  pollBrief?: PollWakeBrief
}

/** Wake one agent. Exposed so non-message-new triggers (kanban card
 *  mentions, calendar dispatches, …) can use the same SSE-or-spawn path. */
export async function wakeAgent(
  agentId: string,
  reason: WakeReason,
  conversationId: string | null = null,
  steerPayload: SteerWakePayload | null = null,
  options: WakeOptions = {},
): Promise<void> {
  return wakeOne(agentId, reason, conversationId, steerPayload, options)
}

// ─── low-priority wake backpressure (FUSE-cap incident 2026-05-20) ──
//
// `idle` and `background_scan` wake reasons are SYNTHETIC — they were
// generated by the server's own schedulers, not by a real user
// message. During a cumora-server crashloop, idle ticks accumulate in
// the schedulers' clock backlog, and on recovery they fire all at
// once: the idle scheduler can issue a wake per agent per tenant in
// rapid succession, the scanner the same. Each wake → Redis publish →
// a daemon wake-stream event.
//
// The fix is a hard cap on synthetic wakes per cumora-server process
// per minute. User-facing reasons (`message.new`, `manual`) are NEVER
// rate-limited — they correspond to a real user action and must go
// through promptly. Per-process counter is fine because the actual
// scheduler scope (idle.ts, scanner.ts) IS per-process; multiple
// replicas multiply the budget naturally (a 2-replica deploy gets
// 2 × LOW_PRIORITY_WAKE_BUDGET_PER_MIN cluster-wide).
const LOW_PRIORITY_WAKE_BUDGET_PER_MIN = 20
let lowPriWindowStart = Date.now()
let lowPriUsed = 0
let lowPriDroppedInWindow = 0

// Agent turn rate limit — a CONTENT-BLIND cost floor, not a loop decision.
// Whether a thread is "a loop" and whether to reply is the small model's call
// (it sees the per-conversation "thread heat" signal and goes quiet on an
// agent-only thread). This limit only bounds how often any one agent can be
// activated by AGENT-driven traffic, so a runaway (or a model that won't stop)
// can't burn unbounded cost. It never looks at message content, and
// human-driven wakes are never throttled. Generous enough that normal use never
// trips it; low enough to cap a ping-pong.
const AGENT_TURN_RATE_PER_MINUTE = 30

/** Consume one agent-turn token (rolling 60s window). Returns false when the
 *  agent is over its content-blind activation budget. Fail-open on Redis errors.
 *  Shared by the cloud fan-out and the BYOA triage endpoint so one agent has one
 *  budget across both paths. */
export async function consumeAgentTurnToken(agentId: string): Promise<boolean> {
  try {
    const key = `cumora:turn-rate:${agentId}`
    const count = await redis.incr(key)
    if (count === 1) await redis.expire(key, 60).catch(() => { /* best-effort */ })
    return count <= AGENT_TURN_RATE_PER_MINUTE
  } catch {
    return true // fail-open
  }
}

/** Returns true if a low-priority wake is allowed under the current
 *  rolling 60s budget. Mutates internal counters. Exported for tests. */
export function _consumeLowPriorityWakeBudget(now: number = Date.now()): boolean {
  if (now - lowPriWindowStart >= 60_000) {
    if (lowPriDroppedInWindow > 0) {
      console.warn(`[scheduler] low-priority wake budget window closing: used=${lowPriUsed} dropped=${lowPriDroppedInWindow}`)
    }
    lowPriWindowStart = now
    lowPriUsed = 0
    lowPriDroppedInWindow = 0
  }
  if (lowPriUsed >= LOW_PRIORITY_WAKE_BUDGET_PER_MIN) {
    lowPriDroppedInWindow++
    return false
  }
  lowPriUsed++
  return true
}

/** Test-only reset. Sets the window start to 0 (epoch) so the next
 *  consume() call — regardless of the `now` value the test passes —
 *  always rolls into a fresh window. In production this function is
 *  never called and `lowPriWindowStart` retains its `Date.now()`
 *  initial value, so rollovers happen on real wall-clock time. */
export function _resetLowPriorityWakeBudgetForTests(): void {
  lowPriWindowStart = 0
  lowPriUsed = 0
  lowPriDroppedInWindow = 0
}

async function wakeOne(
  agentId: string,
  reason: WakeReason,
  conversationId: string | null,
  steerPayload: SteerWakePayload | null = null,
  options: WakeOptions = {},
): Promise<void> {
  // Synthetic wakes can be dropped under load — the next idle tick
  // or next scanner pass will re-evaluate. Real wakes never are.
  if ((reason === 'idle' || reason === 'background_scan') && !_consumeLowPriorityWakeBudget()) {
    console.warn(`[scheduler] ${agentId} ${reason} wake dropped: budget ${LOW_PRIORITY_WAKE_BUDGET_PER_MIN}/min exceeded`)
    return
  }
  const wakePayload = {
    kind: 'wake' as const,
    reason,
    conversationId,
    ...(options.idleReason ? { idleReason: options.idleReason } : {}),
    ...(options.backgroundBrief ? { backgroundBrief: options.backgroundBrief } : {}),
    ...(options.pollBrief ? { pollBrief: options.pollBrief } : {}),
  }
  const delivered = await deliverWake(agentId, wakePayload)

  // Steering: if the agent's daemon is currently mid-turn (busy lease in
  // Redis), ALSO publish the message body as a steer event so the
  // running engine session can inject it at the next hop boundary. Steer is
  // additive to wake — the wake gets the daemon's drain loop spinning,
  // and the steer carries the actual content. If the agent is idle the
  // steer payload is harmless (queue gets discarded by the next turn).
  //
  // STEER_ENABLED kill-switch: if env says false, never publish a
  // steer. Wake still fires; the message is in the DB; the agent's
  // next turn picks it up via loadInbox normally. Use this knob to
  // disable steering during an incident without a redeploy.
  if (env.STEER_ENABLED && steerPayload && delivered > 0) {
    const busy = await isAgentBusy(agentId).catch(() => false)
    if (busy) {
      // Per-agent rate limit: at most STEER_RATE_PER_MINUTE steers
      // delivered in any rolling 60s window. Above that, fall through
      // to wake-only (message is still in DB → next wake picks it up).
      // Without this, a spam loop could saturate the daemon's steer
      // batch caps within seconds and the agent's runtime budget burns down.
      const allowed = await consumeSteerRateToken(agentId)
      if (!allowed) {
        console.warn(`[scheduler] steer rate-limited for ${agentId}; falling back to wake-only`)
      } else {
        await deliverSteer(agentId, steerPayload).catch((err) =>
          console.warn(`[scheduler] deliverSteer(${agentId}) failed:`,
            err instanceof Error ? err.message : err),
        )
        // Visible acknowledgement: the steer payload won't actually be
        // injected into the LLM context until the next hop boundary
        // (the daemon's engine drains between LLM iterations, not
        // mid-tool). For a long-running tool call that boundary could
        // be minutes away, during which the user sees nothing at all
        // and the agent reads as "silent."
        //
        // Fire a typing indicator on the source conversation so the
        // renderer immediately shows "<agent> is typing…" — proof to
        // the human that their steer was received and is queued. The
        // typing event auto-expires in the renderer (no `done:true`
        // teardown needed); when the agent eventually replies, the
        // typing indicator gets replaced by the new message naturally.
        if (steerPayload.conversationId) {
          await publish(CH_TYPING, {
            type: 'typing',
            conversationId: steerPayload.conversationId,
            agentId,
            done: false,
            companyId: steerPayload.companyId,
          }).catch((err) =>
            console.warn(`[scheduler] steer-ack publishTyping(${agentId}) failed:`,
              err instanceof Error ? err.message : err),
          )
        }
      }
    }
  }

  if (delivered > 0) return

  // BYOA is the only execution tier (ADR 0003). If delivered === 0 the
  // agent's daemon simply isn't subscribed right now (host offline /
  // asleep) — there's nothing to spin up. The wake is durable via the
  // inbox, so the daemon catches up on its next reconnect drain.
  console.log(`[scheduler] ${agentId} daemon offline — wake deferred to reconnect`)
}

/** Multi-instance dedup: every cumora-server replica subscribes to
 *  CH_MESSAGE_NEW, so a single message.new fan-outs to N servers.
 *  Without this guard each replica would call wake() →
 *  deliverWake (Redis publish) independently — the agent's daemon
 *  ends up receiving N copies of the wake event (drain folds via
 *  pendingRerun, so it's correctness-safe but wasteful).
 *
 *  Fix: SETNX a key per message id; only the first replica that
 *  claims it proceeds. TTL=60s reaps the key automatically. */
async function claimAndWake(payload: MessageNewEvent): Promise<void> {
  const key = `cumora:wake-claim:${payload.message.id}`
  const claimed = await redis.set(key, '1', 'EX', 60, 'NX').catch(() => null)
  if (claimed === null) return     // another replica owns this wake
  await wake(payload)
}

// ─── author-name cache (Fix #10) ─────────────────────────────────────
//
// Phase 4 originally did `SELECT name FROM participants WHERE id = $1`
// for every new message to resolve the display name for the steer
// prefix. That's N+1 per group-chat message (one query per agent
// member that gets a steer). participants.name changes rarely, so a
// small LRU with a 5-minute TTL collapses the N+1 into ~0 queries in
// steady state. Cache miss is still correct — falls back to authorId.

interface CachedName { name: string; expiresAt: number }
const AUTHOR_NAME_CACHE_TTL_MS = 5 * 60_000
const AUTHOR_NAME_CACHE_MAX = 5_000 // rough cap on a single-process Map
const authorNameCache = new Map<string, CachedName>()

/** Exported for testability. Lookup happens at most once per
 *  authorId per AUTHOR_NAME_CACHE_TTL_MS, with a capacity-trim pass
 *  on overflow. Returns authorId on any DB error so the steer
 *  prefix never breaks. */
export async function resolveAuthorName(authorId: string): Promise<string> {
  const now = Date.now()
  const hit = authorNameCache.get(authorId)
  if (hit && hit.expiresAt > now) return hit.name
  // Best-effort DB read. On error we cache nothing (so the next
  // message retries) and return the id as fallback.
  try {
    const { rows } = await pool.query<{ name: string | null }>(
      `SELECT name FROM participants WHERE id = $1 LIMIT 1`, [authorId],
    )
    const name = rows[0]?.name || authorId
    // Opportunistic capacity trim — when the map exceeds the cap,
    // drop everything that's expired; if still over, drop the
    // OLDEST entries (Map iteration is insertion-ordered, so the
    // first entries are the oldest).
    if (authorNameCache.size >= AUTHOR_NAME_CACHE_MAX) {
      for (const [k, v] of authorNameCache) {
        if (v.expiresAt <= now) authorNameCache.delete(k)
      }
      while (authorNameCache.size >= AUTHOR_NAME_CACHE_MAX) {
        const firstKey = authorNameCache.keys().next().value
        if (firstKey === undefined) break
        authorNameCache.delete(firstKey)
      }
    }
    authorNameCache.set(authorId, { name, expiresAt: now + AUTHOR_NAME_CACHE_TTL_MS })
    return name
  } catch {
    return authorId
  }
}

/** Test-only: clear the author-name cache so test cases don't poison
 *  each other. Production code never calls this. */
export function _resetAuthorNameCacheForTests(): void {
  authorNameCache.clear()
}

// ─── steer rate limit (Fix #8) ───────────────────────────────────────
//
// A spam loop (compromised account, runaway script, etc.) could fire
// hundreds of messages/sec at one agent. Even with MAX_BATCHES_PER_TURN
// and steer batch caps limiting per-turn consumption, the network +
// Redis pub/sub bandwidth + the agent's hop budget would still burn.
// Rate limit at the publish edge: at most STEER_RATE_PER_MINUTE steers
// dispatched per agent in any rolling 60s window. Beyond that, fall
// through to wake-only (message stays in DB → next wake handles).

const STEER_RATE_PER_MINUTE = 30

/** Attempts to consume one steer-rate token for the agent. Returns
 *  true if allowed, false if the rate limit is exceeded. Uses an
 *  atomic Lua-like INCR-and-check, which on first call sets a 60s
 *  TTL — so the counter naturally resets. Fail-open on Redis errors
 *  (steers continue; the wake path is correct anyway). */
async function consumeSteerRateToken(agentId: string): Promise<boolean> {
  try {
    const key = `cumora:steer-rate:${agentId}`
    // INCR is atomic; we set the TTL only on the FIRST increment so
    // the window doesn't get reset on every call. EXPIRE returns 1
    // if the TTL was applied, 0 if the key already had one or didn't
    // exist. Race-safe enough at the per-second granularity we need.
    const count = await redis.incr(key)
    if (count === 1) {
      await redis.expire(key, 60).catch(() => { /* best-effort */ })
    }
    return count <= STEER_RATE_PER_MINUTE
  } catch {
    return true // fail-open
  }
}

/** Test-only: clear the rate-limit counter for an agent so tests
 *  don't poison each other. Production never calls this. */
export async function _resetSteerRateForTests(agentId: string): Promise<void> {
  try { await redis.del(`cumora:steer-rate:${agentId}`) } catch { /* ignore */ }
}

async function wake(payload: MessageNewEvent): Promise<void> {
  const conversationId = payload.conversationId
  const authorId = payload.message.authorId
  const messageKind = payload.message.kind
  const messageBody = payload.message.body
  const messageId = payload.message.id

  // Steering: build a steer payload only for user-visible message
  // kinds — system notices (quota exhausted, etc.) are noise the
  // model doesn't need re-injected mid-turn. Resolve the author's
  // display name via the cache above so a group chat with N agents
  // doesn't trigger N participants-lookups per message.
  let steerPayload: SteerWakePayload | null = null
  if (messageKind !== 'system' && messageBody && messageBody.length > 0) {
    const authorName = await resolveAuthorName(authorId)
    steerPayload = { messageId, conversationId, authorName, body: messageBody, companyId: payload.companyId ?? '' }
  }

  const { rows: convoRows } = await pool.query<{ members: string[]; kind: string; muted_agent_ids: string[] }>(
    `SELECT c.members, c.kind,
            COALESCE(array_agg(mu.user_id) FILTER (WHERE mu.user_id IS NOT NULL), ARRAY[]::text[]) AS muted_agent_ids
       FROM conversations c
       LEFT JOIN conversation_mutes mu ON mu.conversation_id = c.id
        AND (mu.muted_until IS NULL OR mu.muted_until > NOW())
      WHERE c.id = $1
      GROUP BY c.id`,
    [conversationId],
  )
  const conversation = convoRows[0]
  const members = conversation?.members ?? []
  const mutedAgentIds = new Set(conversation?.muted_agent_ids ?? [])
  let quotedAuthorId = payload.message.quoted?.authorId ?? null
  if (!quotedAuthorId && payload.message.quotedMessageId && mutedAgentIds.size > 0) {
    const { rows } = await pool.query<{ author_id: string }>(
      `SELECT author_id FROM messages WHERE id = $1 AND conversation_id = $2`,
      [payload.message.quotedMessageId, conversationId],
    )
    quotedAuthorId = rows[0]?.author_id ?? null
  }
  const agentRecipients: string[] = []
  for (const m of members) {
    if (m === authorId) continue
    if (!(await isAgent(m))) continue
    if (mutedAgentIds.has(m) && !shouldDeliverToMutedAgent({
      agentId: m,
      conversationKind: conversation?.kind ?? 'group',
      body: messageBody,
      quotedAuthorId,
    })) continue
    agentRecipients.push(m)
  }

  // Whether to reply into an agent-only thread is the small model's decision
  // (it sees the per-conversation "thread heat" signal and goes quiet). The
  // scheduler no longer makes that call — it only applies a content-blind cost
  // floor: when an AGENT's message would wake peers, drop the wake for any
  // recipient that is over its activation budget, so a runaway can't burn
  // unbounded cost. Human-driven wakes are NEVER throttled.
  const authorIsAgent = await isAgent(authorId)
  let recipients = agentRecipients
  if (authorIsAgent) {
    const allowed = await Promise.all(
      agentRecipients.map(async (m) => (await consumeAgentTurnToken(m)) ? m : null),
    )
    recipients = allowed.filter((m): m is string => m !== null)
    const dropped = agentRecipients.length - recipients.length
    if (dropped > 0) {
      console.warn(`[scheduler] turn-rate floor: dropped ${dropped} agent-driven wake(s) in ${conversationId} (over ${AGENT_TURN_RATE_PER_MINUTE}/min)`)
    }
  }

  // Always parallel fan-out. We tried a scheduler-side serial queue
  // for @all (stagger → event-driven Redis state machine) — both
  // worked mechanically but felt like nothing a real team would do.
  // Real coordination happens at the AGENT level: see the room,
  // glance once more before committing, defer when a peer is on it.
  // Those affordances live in the daemon + the `cumora glance` tool +
  // the broadcast etiquette section of the persona prompt — the
  // scheduler wakes every subscribed, non-muted agent at the same time,
  // like a Slack room. A muted agent only passes through for an exact
  // mention or quoted reply.
  await fanOutWake(recipients, conversationId, steerPayload)
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** Muted rooms are genuinely absent from an agent's delivery stream. The
 * only intentional escape hatches are a direct conversation, an explicit
 * @agent-id token, or a reply to one of that agent's messages. Exported so
 * the delivery contract stays regression-testable without Redis/Postgres. */
export function shouldDeliverToMutedAgent(args: {
  agentId: string
  conversationKind: string
  body: string
  quotedAuthorId: string | null
}): boolean {
  if (args.conversationKind === 'direct') return true
  if (args.quotedAuthorId === args.agentId) return true
  const mention = new RegExp(`(^|[^\\w@])@${escapeRegex(args.agentId)}(?![\\w-])`, 'i')
  return mention.test(args.body)
}

export async function fanOutWake(
  recipients: string[],
  conversationId: string,
  steerPayload: SteerWakePayload | null,
): Promise<void> {
  // Bounded fan-out (env.WAKE_FANOUT_CONCURRENCY). Each recipient's
  // wakeOne (Redis publish) runs under one semaphore so a large group /
  // agent reply-storm can't stampede the pg pool. Excess recipients
  // queue and drain at a sustainable rate; a delayed wake still
  // self-heals — the message is durable in the inbox, the daemon
  // drains on reconnect, and the per-message wake-claim TTLs out in
  // 60s. Each daemon triages locally (via /inbox-triage) before
  // spending its engine, so no server-side pre-wake triage is needed.
  await Promise.all(recipients.map((m) => wakeFanoutSem.run(async () => {
    // One recipient failing must not stop the others or escape into
    // the Redis on-message handler.
    try {
      await wakeOne(m, 'message.new', conversationId, steerPayload)
    } catch (err) {
      console.error(`[scheduler] wakeOne(${m}) failed:`, err instanceof Error ? err.message : err)
    }
  })))
}


let started = false
export function startScheduler(): void {
  if (started) return
  started = true
  void sub.subscribe(CH_MESSAGE_NEW, (err) => {
    if (err) console.error('[scheduler] subscribe failed', err)
  })
  // Wake the poll author on every state change. Without this an agent
  // who posts a poll sees the original message land in everyone's
  // inbox but never finds out when votes actually come in — and they
  // can neither nudge laggards mid-poll nor summarize when it closes.
  void sub.subscribe(CH_POLLS, (err) => {
    if (err) console.error('[scheduler] CH_POLLS subscribe failed', err)
  })
  sub.on('message', (channel, raw) => {
    if (channel === CH_MESSAGE_NEW) {
      let payload: MessageNewEvent
      try { payload = JSON.parse(raw) as MessageNewEvent } catch { return }
      if (payload.type !== 'message.new') return
      // fire-and-forget — pool.query inside wake() can transiently
      // reject. We don't want an unhandled
      // rejection here; just log and let the next wake retry. The
      // wake-claim Redis key TTLs out in 60s so a missed wake recovers
      // naturally on the next message in the same convo.
      claimAndWake(payload).catch((err) => {
        console.error(`[scheduler] claimAndWake failed for ${payload.message?.id}:`,
          err instanceof Error ? err.message : err)
      })
      return
    }
    if (channel === CH_POLLS) {
      let payload: PollUpdatedEvent
      try { payload = JSON.parse(raw) as PollUpdatedEvent } catch { return }
      if (payload.type !== 'poll.updated') return
      handlePollUpdated(payload).catch((err) => {
        console.error(`[scheduler] handlePollUpdated failed for ${payload.messageId}:`,
          err instanceof Error ? err.message : err)
      })
      return
    }
  })
  console.log(`[scheduler] mailbox scheduler listening on ${CH_MESSAGE_NEW}, ${CH_POLLS} · runtime=byoa-only`)
}

// ─── poll author wake (real-time vote watching) ──────────────────────
//
// When a poll moves (vote cast, vote changed, poll closed), wake the
// agent who AUTHORED that poll so it can:
//   • watch the tally come in
//   • nudge laggards mid-poll
//   • summarize on close
//
// Filters:
//   • author must be an active agent (humans get UI updates already)
//   • skip when the actor IS the author (we don't self-wake an agent
//     who just voted on their own poll — would also infinite-loop)
//
// Debounce:
//   • vote events claim cumora:poll-vote-wake-claim:<msg> with TTL
//     POLL_VOTE_WAKE_DEBOUNCE_SECONDS. Only the first replica/event
//     within the window wakes; subsequent votes silently drop. The
//     agent's turn reads fresh state via the brief built RIGHT BEFORE
//     the wake (and can call `cumora poll show` for newer state).
//   • close events claim a separate cumora:poll-close-wake-claim:<msg>
//     with a long TTL so cross-replica idempotency holds; closePoll
//     is itself idempotent so a duplicate event is harmless apart
//     from the wasted wake.
const POLL_VOTE_WAKE_DEBOUNCE_SECONDS = 8
const POLL_CLOSE_WAKE_CLAIM_SECONDS = 600

async function handlePollUpdated(event: PollUpdatedEvent): Promise<void> {
  if (!event.companyId) return
  const { rows } = await pool.query<{ author_id: string; members: string[] }>(
    `SELECT m.author_id, c.members
       FROM messages m
       JOIN conversations c ON c.id = m.conversation_id
      WHERE m.id = $1 AND m.company_id = $2`,
    [event.messageId, event.companyId],
  )
  const row = rows[0]
  if (!row) return
  const authorId = row.author_id
  // Skip if author isn't an active agent — humans see the tally
  // update through the WS bridge already.
  if (!(await isAgent(authorId))) return
  // Skip self-wake: if the agent voted on (or closed) their own poll,
  // they already know.
  if (event.actorId && event.actorId === authorId) return

  const isClose = Boolean(event.poll.closedAt)
  const claimKey = isClose
    ? `cumora:poll-close-wake-claim:${event.messageId}`
    : `cumora:poll-vote-wake-claim:${event.messageId}`
  const claimTtl = isClose ? POLL_CLOSE_WAKE_CLAIM_SECONDS : POLL_VOTE_WAKE_DEBOUNCE_SECONDS
  const claimed = await redis.set(claimKey, '1', 'EX', claimTtl, 'NX').catch(() => null)
  if (claimed === null) return     // another replica owned this wake, or debounce window still open

  // Resolve display names for everyone we plan to surface in the
  // brief — author already excluded, voters from the tallies, and
  // pending voters (members − {author} − voters).
  const voterSet = new Set<string>()
  for (const t of event.tallies) {
    for (const v of t.voterIds) voterSet.add(v)
  }
  const pendingIds = row.members.filter((m) => m !== authorId && !voterSet.has(m))
  const idsToResolve = new Set<string>([...voterSet, ...pendingIds])
  if (event.actorId) idsToResolve.add(event.actorId)
  const names = await resolveParticipantNames([...idsToResolve])

  const brief: PollWakeBrief = {
    messageId: event.messageId,
    conversationId: event.conversationId,
    question: event.poll.question,
    mode: event.poll.mode,
    status: isClose ? 'closed' : 'open',
    closedReason: event.poll.closedReason,
    expiresAt: event.poll.expiresAt,
    totalVotes: event.tallies.reduce((s, t) => s + t.count, 0),
    tallies: event.poll.options.map((opt) => {
      const tally = event.tallies.find((t) => t.optionId === opt.id)
      const count = tally?.count ?? 0
      const voters = (tally?.voterIds ?? []).map((id) => ({
        id, name: names.get(id) ?? id,
      }))
      return { optionId: opt.id, text: opt.text, count, voters }
    }),
    pending: pendingIds.map((id) => ({ id, name: names.get(id) ?? id })),
    actor: {
      id: event.actorId,
      name: event.actorId ? (names.get(event.actorId) ?? event.actorId) : null,
    },
    phase: isClose ? 'close' : 'vote',
  }

  await wakeAgent(authorId, 'poll.updated', event.conversationId, null, { pollBrief: brief })
}

/** Batch-lookup participant display names. Falls back to the id on
 *  miss/error so the brief is always renderable. Uses the same cache
 *  as resolveAuthorName for any ids already there. */
async function resolveParticipantNames(ids: string[]): Promise<Map<string, string>> {
  const out = new Map<string, string>()
  if (ids.length === 0) return out
  const now = Date.now()
  const missing: string[] = []
  for (const id of ids) {
    const hit = authorNameCache.get(id)
    if (hit && hit.expiresAt > now) {
      out.set(id, hit.name)
    } else {
      missing.push(id)
    }
  }
  if (missing.length === 0) return out
  try {
    const { rows } = await pool.query<{ id: string; name: string | null }>(
      `SELECT id, name FROM participants WHERE id = ANY($1::text[])`,
      [missing],
    )
    for (const r of rows) {
      const name = r.name || r.id
      authorNameCache.set(r.id, { name, expiresAt: now + AUTHOR_NAME_CACHE_TTL_MS })
      out.set(r.id, name)
    }
    for (const id of missing) {
      if (!out.has(id)) out.set(id, id)     // unresolved → fall back to id
    }
  } catch {
    for (const id of missing) out.set(id, id)
  }
  return out
}
