//go:build go1.22

// Package runtimecontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package runtimecontract

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 看板议程(领卡视角)
	// (GET /runtime/agenda)
	LoadAgenda(w http.ResponseWriter, r *http.Request)
	// 上报领卡裁决
	// (POST /runtime/agenda/verdict)
	AgendaVerdict(w http.ResponseWriter, r *http.Request)
	// 清忙租约
	// (POST /runtime/busy/clear)
	BusyClear(w http.ResponseWriter, r *http.Request)
	// 忙租约心跳(steer 判定)
	// (POST /runtime/busy/heartbeat)
	BusyHeartbeat(w http.ResponseWriter, r *http.Request)
	// cumora CLI 出口(world actions;剥 --as)
	// (POST /runtime/cli)
	RuntimeCli(w http.ResponseWriter, r *http.Request)
	// 房间氛围
	// (GET /runtime/climate)
	LoadClimate(w http.ResponseWriter, r *http.Request)
	// 会话上下文
	// (POST /runtime/context)
	LoadContext(w http.ResponseWriter, r *http.Request)
	// 会话→公司
	// (POST /runtime/conversation/company-id)
	ResolveConversationCompany(w http.ResponseWriter, r *http.Request)
	// agent 已读
	// (POST /runtime/conversation/mark-read)
	RuntimeMarkRead(w http.ResponseWriter, r *http.Request)
	// 记事件
	// (POST /runtime/events)
	RecordEvent(w http.ResponseWriter, r *http.Request)
	// 名册头像
	// (POST /runtime/faces)
	LoadFaces(w http.ResponseWriter, r *http.Request)
	// 收件箱
	// (GET /runtime/inbox)
	LoadInbox(w http.ResponseWriter, r *http.Request)
	// 本地 triage 载荷(上下文打包)
	// (GET /runtime/inbox-triage/payload)
	InboxTriagePayload(w http.ResponseWriter, r *http.Request)
	// 记 LLM 调用台账
	// (POST /runtime/llm-calls)
	RecordLlmCall(w http.ResponseWriter, r *http.Request)
	// 记忆检索
	// (POST /runtime/memory/query)
	MemoryQuery(w http.ResponseWriter, r *http.Request)
	// 系统通知
	// (POST /runtime/notices)
	PostNotice(w http.ResponseWriter, r *http.Request)
	// agent 人设
	// (GET /runtime/persona)
	LoadPersona(w http.ResponseWriter, r *http.Request)
	// 团队名册
	// (GET /runtime/roster)
	LoadRoster(w http.ResponseWriter, r *http.Request)
	// 开 run
	// (POST /runtime/runs)
	StartRun(w http.ResponseWriter, r *http.Request)
	// 结 run
	// (POST /runtime/runs/{runId}/finish)
	FinishRun(w http.ResponseWriter, r *http.Request, runId string)
	// run 心跳
	// (POST /runtime/runs/{runId}/heartbeat)
	RunHeartbeat(w http.ResponseWriter, r *http.Request, runId string)
	// agent 技能清单
	// (GET /runtime/skills)
	LoadSkills(w http.ResponseWriter, r *http.Request)
	// 上报状态
	// (POST /runtime/status)
	ReportStatus(w http.ResponseWriter, r *http.Request)
	// 状态心跳
	// (POST /runtime/status/heartbeat)
	StatusHeartbeat(w http.ResponseWriter, r *http.Request)
	// 系统提示词
	// (GET /runtime/system-prompt)
	LoadSystemPrompt(w http.ResponseWriter, r *http.Request)
	// 标记思考中
	// (POST /runtime/thinking/mark)
	ThinkingMark(w http.ResponseWriter, r *http.Request)
	// 窥思考态
	// (GET /runtime/thinking/peek)
	ThinkingPeek(w http.ResponseWriter, r *http.Request)
	// 解除思考
	// (POST /runtime/thinking/unmark)
	ThinkingUnmark(w http.ResponseWriter, r *http.Request)
	// 记 triage 台账
	// (POST /runtime/triage)
	RecordTriage(w http.ResponseWriter, r *http.Request)
	// agent 输入态
	// (POST /runtime/typing)
	RuntimeTyping(w http.ResponseWriter, r *http.Request)
	// SSE 唤醒流(见 info 的事件面策略;长连接)
	// (GET /runtime/wake-stream)
	WakeStream(w http.ResponseWriter, r *http.Request)
	// 原子领工
	// (POST /runtime/worklog/claim)
	WorklogClaim(w http.ResponseWriter, r *http.Request)
	// 窥工单
	// (GET /runtime/worklog/peek)
	WorklogPeek(w http.ResponseWriter, r *http.Request)
	// 释放工
	// (POST /runtime/worklog/release)
	WorklogRelease(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoadAgenda operation middleware
func (siw *ServerInterfaceWrapper) LoadAgenda(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadAgenda(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgendaVerdict operation middleware
func (siw *ServerInterfaceWrapper) AgendaVerdict(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgendaVerdict(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BusyClear operation middleware
func (siw *ServerInterfaceWrapper) BusyClear(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BusyClear(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BusyHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) BusyHeartbeat(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BusyHeartbeat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RuntimeCli operation middleware
func (siw *ServerInterfaceWrapper) RuntimeCli(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RuntimeCli(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadClimate operation middleware
func (siw *ServerInterfaceWrapper) LoadClimate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadClimate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadContext operation middleware
func (siw *ServerInterfaceWrapper) LoadContext(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadContext(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveConversationCompany operation middleware
func (siw *ServerInterfaceWrapper) ResolveConversationCompany(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveConversationCompany(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RuntimeMarkRead operation middleware
func (siw *ServerInterfaceWrapper) RuntimeMarkRead(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RuntimeMarkRead(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordEvent operation middleware
func (siw *ServerInterfaceWrapper) RecordEvent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadFaces operation middleware
func (siw *ServerInterfaceWrapper) LoadFaces(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadFaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadInbox operation middleware
func (siw *ServerInterfaceWrapper) LoadInbox(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadInbox(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InboxTriagePayload operation middleware
func (siw *ServerInterfaceWrapper) InboxTriagePayload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InboxTriagePayload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordLlmCall operation middleware
func (siw *ServerInterfaceWrapper) RecordLlmCall(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordLlmCall(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MemoryQuery operation middleware
func (siw *ServerInterfaceWrapper) MemoryQuery(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MemoryQuery(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNotice operation middleware
func (siw *ServerInterfaceWrapper) PostNotice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNotice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadPersona operation middleware
func (siw *ServerInterfaceWrapper) LoadPersona(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadPersona(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadRoster operation middleware
func (siw *ServerInterfaceWrapper) LoadRoster(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadRoster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartRun operation middleware
func (siw *ServerInterfaceWrapper) StartRun(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishRun operation middleware
func (siw *ServerInterfaceWrapper) FinishRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) RunHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunHeartbeat(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadSkills operation middleware
func (siw *ServerInterfaceWrapper) LoadSkills(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadSkills(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportStatus operation middleware
func (siw *ServerInterfaceWrapper) ReportStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) StatusHeartbeat(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusHeartbeat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadSystemPrompt operation middleware
func (siw *ServerInterfaceWrapper) LoadSystemPrompt(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadSystemPrompt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ThinkingMark operation middleware
func (siw *ServerInterfaceWrapper) ThinkingMark(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ThinkingMark(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ThinkingPeek operation middleware
func (siw *ServerInterfaceWrapper) ThinkingPeek(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ThinkingPeek(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ThinkingUnmark operation middleware
func (siw *ServerInterfaceWrapper) ThinkingUnmark(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ThinkingUnmark(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordTriage operation middleware
func (siw *ServerInterfaceWrapper) RecordTriage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordTriage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RuntimeTyping operation middleware
func (siw *ServerInterfaceWrapper) RuntimeTyping(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RuntimeTyping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WakeStream operation middleware
func (siw *ServerInterfaceWrapper) WakeStream(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WakeStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorklogClaim operation middleware
func (siw *ServerInterfaceWrapper) WorklogClaim(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorklogClaim(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorklogPeek operation middleware
func (siw *ServerInterfaceWrapper) WorklogPeek(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorklogPeek(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WorklogRelease operation middleware
func (siw *ServerInterfaceWrapper) WorklogRelease(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentRuntimeJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WorklogRelease(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/runtime/agenda", wrapper.LoadAgenda)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/agenda/verdict", wrapper.AgendaVerdict)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/busy/clear", wrapper.BusyClear)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/busy/heartbeat", wrapper.BusyHeartbeat)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/cli", wrapper.RuntimeCli)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/climate", wrapper.LoadClimate)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/context", wrapper.LoadContext)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/conversation/company-id", wrapper.ResolveConversationCompany)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/conversation/mark-read", wrapper.RuntimeMarkRead)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/events", wrapper.RecordEvent)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/faces", wrapper.LoadFaces)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/inbox", wrapper.LoadInbox)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/inbox-triage/payload", wrapper.InboxTriagePayload)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/llm-calls", wrapper.RecordLlmCall)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/memory/query", wrapper.MemoryQuery)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/notices", wrapper.PostNotice)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/persona", wrapper.LoadPersona)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/roster", wrapper.LoadRoster)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/runs", wrapper.StartRun)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/runs/{runId}/finish", wrapper.FinishRun)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/runs/{runId}/heartbeat", wrapper.RunHeartbeat)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/skills", wrapper.LoadSkills)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/status", wrapper.ReportStatus)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/status/heartbeat", wrapper.StatusHeartbeat)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/system-prompt", wrapper.LoadSystemPrompt)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/thinking/mark", wrapper.ThinkingMark)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/thinking/peek", wrapper.ThinkingPeek)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/thinking/unmark", wrapper.ThinkingUnmark)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/triage", wrapper.RecordTriage)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/typing", wrapper.RuntimeTyping)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/wake-stream", wrapper.WakeStream)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/worklog/claim", wrapper.WorklogClaim)
	m.HandleFunc("GET "+options.BaseURL+"/runtime/worklog/peek", wrapper.WorklogPeek)
	m.HandleFunc("POST "+options.BaseURL+"/runtime/worklog/release", wrapper.WorklogRelease)

	return m
}
