//go:build go1.22

// Package boardscontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package boardscontract

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 看板列表
	// (GET /api/boards)
	ListBoards(w http.ResponseWriter, r *http.Request)
	// 建看板
	// (POST /api/boards)
	CreateBoard(w http.ResponseWriter, r *http.Request)
	// 删卡
	// (DELETE /api/boards/{bid}/cards/{cid})
	DeleteCard(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 改卡(标题/描述/列/位/指派)
	// (PATCH /api/boards/{bid}/cards/{cid})
	UpdateCard(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 卡评论
	// (GET /api/boards/{bid}/cards/{cid}/comments)
	ListCardComments(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 加评论(@提及解析)
	// (POST /api/boards/{bid}/cards/{cid}/comments)
	AddCardComment(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 删评论
	// (DELETE /api/boards/{bid}/cards/{cid}/comments/{mid})
	DeleteCardComment(w http.ResponseWriter, r *http.Request, bid string, cid string, mid string)
	// 加列
	// (POST /api/boards/{bid}/columns)
	AddBoardColumn(w http.ResponseWriter, r *http.Request, bid string)
	// 删列(卡随列走)
	// (DELETE /api/boards/{bid}/columns/{cid})
	DeleteBoardColumn(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 改列(标题/位置)
	// (PATCH /api/boards/{bid}/columns/{cid})
	UpdateBoardColumn(w http.ResponseWriter, r *http.Request, bid string, cid string)
	// 删看板
	// (DELETE /api/boards/{id})
	DeleteBoard(w http.ResponseWriter, r *http.Request, id string)
	// 看板快照(列+卡)
	// (GET /api/boards/{id})
	GetBoard(w http.ResponseWriter, r *http.Request, id string)
	// 改看板
	// (PATCH /api/boards/{id})
	UpdateBoard(w http.ResponseWriter, r *http.Request, id string)
	// 建卡
	// (POST /api/boards/{id}/cards)
	CreateCard(w http.ResponseWriter, r *http.Request, id string)
	// 跨看板卡反查(领卡 triage 入口)
	// (GET /api/cards/{id})
	GetBoardCard(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBoards operation middleware
func (siw *ServerInterfaceWrapper) ListBoards(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBoards(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBoard operation middleware
func (siw *ServerInterfaceWrapper) CreateBoard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBoard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCard operation middleware
func (siw *ServerInterfaceWrapper) DeleteCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCard(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCard operation middleware
func (siw *ServerInterfaceWrapper) UpdateCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCard(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCardComments operation middleware
func (siw *ServerInterfaceWrapper) ListCardComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCardComments(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddCardComment operation middleware
func (siw *ServerInterfaceWrapper) AddCardComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddCardComment(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCardComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteCardComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	// ------------- Path parameter "mid" -------------
	var mid string

	err = runtime.BindStyledParameterWithOptions("simple", "mid", r.PathValue("mid"), &mid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCardComment(w, r, bid, cid, mid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBoardColumn operation middleware
func (siw *ServerInterfaceWrapper) AddBoardColumn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBoardColumn(w, r, bid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBoardColumn operation middleware
func (siw *ServerInterfaceWrapper) DeleteBoardColumn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBoardColumn(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBoardColumn operation middleware
func (siw *ServerInterfaceWrapper) UpdateBoardColumn(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bid" -------------
	var bid string

	err = runtime.BindStyledParameterWithOptions("simple", "bid", r.PathValue("bid"), &bid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bid", Err: err})
		return
	}

	// ------------- Path parameter "cid" -------------
	var cid string

	err = runtime.BindStyledParameterWithOptions("simple", "cid", r.PathValue("cid"), &cid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBoardColumn(w, r, bid, cid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBoard operation middleware
func (siw *ServerInterfaceWrapper) DeleteBoard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBoard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBoard operation middleware
func (siw *ServerInterfaceWrapper) GetBoard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBoard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBoard operation middleware
func (siw *ServerInterfaceWrapper) UpdateBoard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBoard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCard operation middleware
func (siw *ServerInterfaceWrapper) CreateCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBoardCard operation middleware
func (siw *ServerInterfaceWrapper) GetBoardCard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBoardCard(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/boards", wrapper.ListBoards)
	m.HandleFunc("POST "+options.BaseURL+"/api/boards", wrapper.CreateBoard)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/boards/{bid}/cards/{cid}", wrapper.DeleteCard)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/boards/{bid}/cards/{cid}", wrapper.UpdateCard)
	m.HandleFunc("GET "+options.BaseURL+"/api/boards/{bid}/cards/{cid}/comments", wrapper.ListCardComments)
	m.HandleFunc("POST "+options.BaseURL+"/api/boards/{bid}/cards/{cid}/comments", wrapper.AddCardComment)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/boards/{bid}/cards/{cid}/comments/{mid}", wrapper.DeleteCardComment)
	m.HandleFunc("POST "+options.BaseURL+"/api/boards/{bid}/columns", wrapper.AddBoardColumn)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/boards/{bid}/columns/{cid}", wrapper.DeleteBoardColumn)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/boards/{bid}/columns/{cid}", wrapper.UpdateBoardColumn)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/boards/{id}", wrapper.DeleteBoard)
	m.HandleFunc("GET "+options.BaseURL+"/api/boards/{id}", wrapper.GetBoard)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/boards/{id}", wrapper.UpdateBoard)
	m.HandleFunc("POST "+options.BaseURL+"/api/boards/{id}/cards", wrapper.CreateCard)
	m.HandleFunc("GET "+options.BaseURL+"/api/cards/{id}", wrapper.GetBoardCard)

	return m
}
