//go:build go1.22

// Package hrcontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package hrcontract

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// HR Agent 配置读(状态卡;owner/admin)
	// (GET /api/hr)
	GetHrAgent(w http.ResponseWriter, r *http.Request)
	// HR Agent 配置写(owner/admin;prompt/computer/engine)
	// (PUT /api/hr)
	PutHrAgentConfig(w http.ResponseWriter, r *http.Request)
	// 自动运行配置读(周期+三钩子阈值;owner/admin)
	// (GET /api/hr/autorun)
	GetHrAutoRun(w http.ResponseWriter, r *http.Request)
	// 自动运行配置写(owner/admin;部分更新,0=关对应项)
	// (PUT /api/hr/autorun)
	PutHrAutoRunConfig(w http.ResponseWriter, r *http.Request)
	// 手动跑一轮自动评估扫描(owner/admin;生产由 60s worker 周期执行,此端点强制到期)
	// (POST /api/hr/autorun/tick)
	TriggerHrAutoRunTick(w http.ResponseWriter, r *http.Request)
	// 岗位层变更历史(owner/admin;可按 agent 过滤)
	// (GET /api/hr/changes)
	ListHrChanges(w http.ResponseWriter, r *http.Request, params ListHrChangesParams)
	// 一键回滚一次岗位层变更(owner/admin;回滚本身入历史)
	// (POST /api/hr/changes/{id}/revert)
	RevertHrChange(w http.ResponseWriter, r *http.Request, id string)
	// 评估轮列表(owner/admin)
	// (GET /api/hr/evaluations)
	ListHrEvaluations(w http.ResponseWriter, r *http.Request)
	// 手动触发评估(单个/全员;owner/admin;在飞互斥)
	// (POST /api/hr/evaluations)
	CreateHrEvaluation(w http.ResponseWriter, r *http.Request)
	// 评估轮详情(含 payload 与输入快照;owner/admin)
	// (GET /api/hr/evaluations/{id})
	GetHrEvaluation(w http.ResponseWriter, r *http.Request, id string)
	// 招人/淘汰提案列表(owner/admin;可按状态过滤)
	// (GET /api/hr/proposals)
	ListHrProposals(w http.ResponseWriter, r *http.Request, params ListHrProposalsParams)
	// 批准提案并执行(owner/admin;hire=同源建 agent 全流程,offboard=软删可复聘)
	// (POST /api/hr/proposals/{id}/approve)
	ApproveHrProposal(w http.ResponseWriter, r *http.Request, id string)
	// 拒绝提案(owner/admin;只留处置痕迹)
	// (POST /api/hr/proposals/{id}/reject)
	RejectHrProposal(w http.ResponseWriter, r *http.Request, id string)
	// owner 主观评分列表(owner/admin)
	// (GET /api/hr/ratings)
	ListHrRatings(w http.ResponseWriter, r *http.Request)
	// upsert owner 主观评分(打分+评语;owner/admin)
	// (PUT /api/hr/ratings/{agentId})
	PutHrRating(w http.ResponseWriter, r *http.Request, agentId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHrAgent operation middleware
func (siw *ServerInterfaceWrapper) GetHrAgent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHrAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutHrAgentConfig operation middleware
func (siw *ServerInterfaceWrapper) PutHrAgentConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutHrAgentConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHrAutoRun operation middleware
func (siw *ServerInterfaceWrapper) GetHrAutoRun(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHrAutoRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutHrAutoRunConfig operation middleware
func (siw *ServerInterfaceWrapper) PutHrAutoRunConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutHrAutoRunConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerHrAutoRunTick operation middleware
func (siw *ServerInterfaceWrapper) TriggerHrAutoRunTick(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerHrAutoRunTick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHrChanges operation middleware
func (siw *ServerInterfaceWrapper) ListHrChanges(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHrChangesParams

	// ------------- Optional query parameter "agentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "agentId", r.URL.Query(), &params.AgentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHrChanges(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevertHrChange operation middleware
func (siw *ServerInterfaceWrapper) RevertHrChange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevertHrChange(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHrEvaluations operation middleware
func (siw *ServerInterfaceWrapper) ListHrEvaluations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHrEvaluations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHrEvaluation operation middleware
func (siw *ServerInterfaceWrapper) CreateHrEvaluation(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHrEvaluation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHrEvaluation operation middleware
func (siw *ServerInterfaceWrapper) GetHrEvaluation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHrEvaluation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHrProposals operation middleware
func (siw *ServerInterfaceWrapper) ListHrProposals(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHrProposalsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHrProposals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveHrProposal operation middleware
func (siw *ServerInterfaceWrapper) ApproveHrProposal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveHrProposal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectHrProposal operation middleware
func (siw *ServerInterfaceWrapper) RejectHrProposal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectHrProposal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHrRatings operation middleware
func (siw *ServerInterfaceWrapper) ListHrRatings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHrRatings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutHrRating operation middleware
func (siw *ServerInterfaceWrapper) PutHrRating(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", r.PathValue("agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionBearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutHrRating(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/hr", wrapper.GetHrAgent)
	m.HandleFunc("PUT "+options.BaseURL+"/api/hr", wrapper.PutHrAgentConfig)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/autorun", wrapper.GetHrAutoRun)
	m.HandleFunc("PUT "+options.BaseURL+"/api/hr/autorun", wrapper.PutHrAutoRunConfig)
	m.HandleFunc("POST "+options.BaseURL+"/api/hr/autorun/tick", wrapper.TriggerHrAutoRunTick)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/changes", wrapper.ListHrChanges)
	m.HandleFunc("POST "+options.BaseURL+"/api/hr/changes/{id}/revert", wrapper.RevertHrChange)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/evaluations", wrapper.ListHrEvaluations)
	m.HandleFunc("POST "+options.BaseURL+"/api/hr/evaluations", wrapper.CreateHrEvaluation)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/evaluations/{id}", wrapper.GetHrEvaluation)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/proposals", wrapper.ListHrProposals)
	m.HandleFunc("POST "+options.BaseURL+"/api/hr/proposals/{id}/approve", wrapper.ApproveHrProposal)
	m.HandleFunc("POST "+options.BaseURL+"/api/hr/proposals/{id}/reject", wrapper.RejectHrProposal)
	m.HandleFunc("GET "+options.BaseURL+"/api/hr/ratings", wrapper.ListHrRatings)
	m.HandleFunc("PUT "+options.BaseURL+"/api/hr/ratings/{agentId}", wrapper.PutHrRating)

	return m
}
